### ISSUE TITLE
ONNX Export issue for QATv1

### ISSUE THREAD

**Issue by kadarsh007** [TexasInstruments/edgeai-tensorlab#11]
Hi,
I have trained a model using Quantization aware training(QAT) v1. And when i use the model of pt type for prediction, the model works fine. When I export the model in onnx format and use it for inference, there is performance drop in the bounding box detection，especially those bounding box with low confidence. Do you have any suggestions when exporting the model in onnx format?

**Comment by parakh08** [comment]
Hey, were you able to check the accuracy in torch itself for the quantized network. If so, can you compare the difference in output of torch model and onnx from onnx-runtime. I am guessing something could be wrong in the postprocessing itself.

**Comment by kadarsh007** [comment]
Hi Parakh,
Yes, I am able to check accuracy with torch for the quantized network, it works fine for this case. 
Only issue is with performance with onnx(onnx-runtime).
I am using same post processing script for torch as well as onnx-runtime. 
I have opened this query on TI forum here (https://e2e.ti.com/support/processors-group/processors/f/processors-forum/1407586/tda4vm-onnx-export-issue-for-qatv1/5425197#5425197).
