### ISSUE TITLE
mmdetection bug

### ISSUE THREAD

**Issue by cdy-for-grad** [TexasInstruments/edgeai-tensorlab#9]
Great Project, I try your code， when i run YOLOX training， in the process of the validation, the bug is comming.

img_meta[img_id]['batch_input_shape'] = tuple(img.size()[-2:])
  File "/usr/local/lib/python3.8/dist-packages/mmcv/parallel/data_container.py", line 12, in wrapper
    raise AttributeError(
AttributeError: DataContainer has no attribute size for type <class 'list'>

**Comment by mathmanu** [comment]
An update for this repo is coming in a few days with a recent version of mmdetection fork. Please try it and let us know.
